### ISSUE TITLE
os.getcwd() ?

### ISSUE THREAD

**Issue by lee212** [inspiremd/Model-generation#10]
https://github.com/inspiremd/Model-generation/blob/ebc60ed4da6f36344b38647947826cb257ad02e6/esmacs.py#L42

**Comment by lee212** [comment]
parenthesis is missing to execute the method?

**Comment by apbhati1** [comment]
Yes, that was indeed the issue. However, even then it would have not worked with EnTK as apparently the `cwd` is not the same as where the job is executed from. So, the path needed to be hardcoded to make it work using EnTK. Anyway, since we are not using `esmacs.py` anymore, we shouldn't bother about it now.
